/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/meQzLUcbjbH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Slot() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="grid grid-cols-5 gap-2 mb-8">
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
        <div className="w-16 h-16 bg-card rounded-md flex items-center justify-center">
          <div className="w-8 h-8 bg-[#ff4d4d] rounded-full" />
        </div>
      </div>
      <div className="flex items-center justify-between w-full max-w-md px-4">
        <div className="text-2xl font-bold text-primary-foreground">Score: 250</div>
        <div className="flex gap-4">
          <Button variant="outline" className="px-4 py-2 rounded-md">
            New Game
          </Button>
          <Button className="px-4 py-2 rounded-md">Play</Button>
        </div>
      </div>
    </div>
  )
}
